### ISSUE TITLE
undefined reference to `clock_gettime'

### ISSUE THREAD

**Issue by haipome** [Qihoo360/QConf#10]
Linking CXX executable qconf_agent
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-timeval.o): In function `curlx_tvnow':
timeval.c:(.text+0xf): undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make[2]: *** [agent/qconf_agent] Error 1
make[1]: *** [agent/CMakeFiles/qconf_agent.dir/all] Error 2
make: *** [all] Error 2

I think there should hava -lrt in makefile, but I don't know how to fix this.

**Comment by CatKang** [comment]
The error occurs in the build process of curl in CMAKE procedure by the commands bellow:
>./configure  --prefix=**${PROJECT_SOURCE_DIR}**/../deps/curl/_install   --disable-ldap
    --disable-ldaps --without-ssl --without-zlib --without-libidn
>make 
>make install

**${PROJECT_SOURCE_DIR}** is where the **"agent"** source code located

You can performing this manually and add -lrt in the Makefile.
And remove line from 51 to 58 in QConf/agent/CMakeLists.txt accordingly.

Let me know if there still having trouble after that
