### ISSUE TITLE
jdk6下无法报错找不到类

### ISSUE THREAD

**Issue by yangming860101** [Qihoo360/QConf#13]
java.lang.UnsupportedClassVersionError: net/qihoo/qconf/Qconf : Unsupported major.minor version 51.0
qconf client包是在java 1.6.0_45下编译生成，引入工程后再tomcat下运行（java环境还是1.6），报上面的错误，请问怎么解决？

注：
生成环境使用的是jdk1.6，没法升级

**Comment by CatKang** [comment]
J2SE 8 = 52 (0x34 hex),
J2SE 7 = 51 (0x33 hex),
J2SE 6.0 = 50 (0x32 hex),
J2SE 5.0 = 49 (0x31 hex),
JDK 1.4 = 48 (0x30 hex),
JDK 1.3 = 47 (0x2F hex),
JDK 1.2 = 46 (0x2E hex),
JDK 1.1 = 45 (0x2D hex).

51应该是说jdk 7 下编译的，先确认下吧

另外，可以尝试加target参数， javac -target xx XXX

**Comment by CatKang** [comment]
如果仍然有问题，可以联系我
