### ISSUE TITLE
[PHP extension] qconf.so: undefined symbol: qconf_init

### ISSUE THREAD

**Issue by lycboy** [Qihoo360/QConf#16]
PHP and QConf are all installed on non-default path.

When QConf PHP extension installed, run `php -m`, it reported:

```
php: symbol lookup error: /path/to/php/lib/php/extensions/no-debug-non-zts-20131226/qconf.so: undefined symbol: qconf_init
```

I modified the config.m4 file to:

``` shell
PHP_ARG_ENABLE(qconf, whether to enable qconf support,
[  --enable-qconf               Enable qconf support])

PHP_ARG_WITH(libqconf-dir,  for libqconf,
[  --with-libqconf-dir[=DIR]   Set the path to libqconf prefix.], yes)

if test -z "$PHP_DEBUG"
then
  AC_ARG_ENABLE(debug,
  [  --enable-debug          compile with debugging symbols],[
    PHP_DEBUG=$enableval
  ],[    PHP_DEBUG=no
  ])
fi

if test "$PHP_QCONF" != "no"
then
  if test "$PHP_LIBQCONF_DIR" != "no" && test "$PHP_LIBQCONF_DIR" != "yes"
  then
    PHP_LIBQCONF_DIR=$PHP_LIBQCONF_DIR
  else
    PHP_LIBQCONF_DIR="/usr/local/include/qconf"
  fi

  PHP_LIBQCONF_INC=$PHP_LIBQCONF_DIR/include
  PHP_LIBQCONF_LIB=$PHP_LIBQCONF_DIR/lib

  if test ! -r "$PHP_LIBQCONF_INC/qconf.h"
    then
      AC_MSG_ERROR([Can't find qconf headers under "$PHP_LIBQCONF_DIR"])
  fi

  PHP_REQUIRE_CXX()
  PHP_ADD_INCLUDE($PHP_LIBQCONF_INC)
  PHP_ADD_LIBRARY(stdc++, "", EXTRA_LDFLAGS)
  PHP_ADD_LIBRARY_WITH_PATH(qconf, "$PHP_LIBQCONF_LIB", QCONF_SHARED_LIBADD)
  PHP_NEW_EXTENSION(qconf, php_qconf.c $SESSION_EXTRA_FILES, $ext_shared)
  PHP_SUBST(QCONF_SHARED_LIBADD)
fi
```

I use `--with-libqconf-dir` to specify the libqconf PREFIX(not the include directory) to solve the problem.

Hope to help you improve QConf :)

**Comment by CatKang** [comment]
Greate job

Thank you for your advice！

But I'm still confused with the error message.

Have you specify the location of qconf library with the follow command.
 " --enable-static LDFLAGS=/usr/local/qconf/lib/libqconf.a"
as described in https://github.com/Qihoo360/QConf/wiki/QConf-PHP-Doc

**Comment by lycboy** [comment]
Sorry my fault, I didn't carefully read the document...

I think it's a best practice to set the library installed prefix instead of the include path, and no LDFLAGS set manually. Maybe it's still a alternative :)

Thank you very much!

**Comment by CatKang** [comment]
Yeah, I think your solution is much more elegant.

But I found it may not work properly on MacOS with information:
"Library not loaded: libqconf.dylib"

Do you know what's the matter?

Thanks very much

**Comment by lycboy** [comment]
Sorry missed your reply...
I didn't test QConf on OSX. I guess the shared lib of libqconf use .so as it's extension, not the normal extension of OSX shared lib(*.dylib).

**Comment by l19861225q** [comment]
See this [How to install QConf on OSX](http://l19861225q.github.io/2016/08/29/How-to-install-QConf-on-OSX/) ^_^
