### ISSUE TITLE
 单元测试编译头文件引用

### ISSUE THREAD

**Issue by bigpyer** [Qihoo360/QConf#18]
QConf/test/unit/CMakeLists.txt   line 56 include_directories变量中增加以下头文件引用
${GDBM_SOURCE_DIR}/include
${CURL_SOURCE_DIR}/include

防止编译时找不到gdbm和curl的头文件或者找到了系统中已经安装的版本不一致的头文件。

**Comment by CatKang** [comment]
已修复，感谢反馈
