### ISSUE TITLE
[ERROR] Failed to init qconf! ret:201

### ISSUE THREAD

**Issue by laozhizi** [Qihoo360/QConf#22]
[ERROR] Failed to init qconf! ret:201

谁帮解决？

**Comment by CatKang** [comment]
初始化错误，可能是共享内存限制导致的，解决方法参考链接中第二个问题：https://github.com/Qihoo360/QConf/wiki/FAQ

**Comment by microhello** [comment]
@laozhizi 当机器上qconf_agent 没有运行时，也会产生这样的错误信息。
需要先运行 
```sh
agent_cmd.sh start 
```

**Comment by CatKang** [comment]
这个错误大多是由于agent没有启动导致的

**Comment by GodEngine** [comment]
1. $ cd /usr/local/qconf/bin
2. $ sudo chmod 777 agent-cmd.sh
3. $ vim agent-cmd.sh
4. modify the line 355（add "#" before "flock -n -e 200"）
5. save and quit
6. $ sudo sh agent-cmd.sh start
7. good luck

**Comment by jiandandkl** [comment]
mac上使用同级目录的qconf_agent启动就能避免ret:201和某些host获取不了的ret:10的错误

**Comment by wangweiwg** [comment]
怎么解决的呀？
