### ISSUE TITLE
Can you depoly java driver into Maven repository?

### ISSUE THREAD

**Issue by microhello** [Qihoo360/QConf#25]
@CatKang  @chancey 

I use *qconf* in java project. if you deploy java driver jar file into central maven repository ,would be great .
Many thanks.

**Comment by CatKang** [comment]
The jar of qconf contains a dynamic lib in it, and qconf-agent must be installed on current machine, so it is not easy to be deployed into maven repository, do you have any good ideas on this?

**Comment by microhello** [comment]
I have deployed centos platform's java driver to central maven repository currently. Maybe can deploy ubuntu java driver to central repository too. 
```xml
<dependency>
    <groupId>net.qihoo</groupId>
    <artifactId>qconf-driver-java</artifactId>
    <version>1.1.0</version>
</dependency>
```

**Comment by Misfit-John** [comment]
😔Do you have a plan to merge the native lib into java? It's a little hard to use the driver for java user now.
