### ISSUE TITLE
win平台如何使用

### ISSUE THREAD

**Issue by duduwang** [Qihoo360/QConf#26]
我们的开发环境在win平台，请问用源码是否能在win平台编译？

**Comment by bigpyer** [comment]
目前只支持Linux、Mac OSX，还不支持windows

**Comment by duduwang** [comment]
是否考虑windows系统的支持？

**Comment by duduwang** [comment]
@bigpyer 是否方便私信给我邮箱，我们这边可能需要实现windows系统支持

**Comment by bigpyer** [comment]
可以加Qconf官方群 438042718，里面可以获得一手的资料

**Comment by CatKang** [comment]
Qconf的实现非常依赖linux系统，所以短期应该不会支持windows

**Comment by duduwang** [comment]
谢谢回复

**Comment by duduwang** [comment]
http://blog.csdn.net/i_saw_you/article/details/50749591  已经解决，为方便后来人，贴出我的博客地址
