### ISSUE TITLE
cmake error  ： syntax error %error-verbose

### ISSUE THREAD

**Issue by kuaikuairen** [Qihoo360/QConf#28]
YACC     gram.c
**byacc: e - line 26 of "/root/QConf/deps/gdbm/src/gram.y", syntax error
%error-verbose
^**
make[2]: **\* [gram.c] Error 1
make[2]: Leaving directory `/root/QConf/deps/gdbm/src'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
make[1]: Leaving directory`/root/QConf/deps/gdbm'
Making install in po
make[1]: Entering directory `/root/QConf/deps/gdbm/po'
installing de.gmo as /root/QConf/agent/../deps/gdbm/_install/share/locale/de/LC_MESSAGES/gdbm.mo
installing eo.gmo as /root/QConf/agent/../deps/gdbm/_install/share/locale/eo/LC_MESSAGES/gdbm.mo
installing fi.gmo as /root/QConf/agent/../deps/gdbm/_install/share/locale/fi/LC_MESSAGES/gdbm.mo
installing fr.gmo as /root/QConf/agent/../deps/gdbm/_install/share/locale/fr/LC_MESSAGES/gdbm.mo
installing ja.gmo as /root/QConf/agent/../deps/gdbm/_install/share/locale/ja/LC_MESSAGES/gdbm.mo
installing pl.gmo as /root/QConf/agent/../deps/gdbm/_install/share/locale/pl/LC_MESSAGES/gdbm.mo
installing pt_BR.gmo as /root/QConf/agent/../deps/gdbm/_install/share/locale/pt_BR/LC_MESSAGES/gdbm.mo
installing sr.gmo as /root/QConf/agent/../deps/gdbm/_install/share/locale/sr/LC_MESSAGES/gdbm.mo
installing uk.gmo as /root/QConf/agent/../deps/gdbm/_install/share/locale/uk/LC_MESSAGES/gdbm.mo
installing vi.gmo as /root/QConf/agent/../deps/gdbm/_install/share/locale/vi/LC_MESSAGES/gdbm.mo
if test "gdbm" = "gettext-tools"; then \
          /bin/mkdir -p /root/QConf/agent/../deps/gdbm/_install/share/gettext/po; \
          for file in Makefile.in.in remove-potcdate.sin quot.sed boldquot.sed en@quot.header en@boldquot.header insert-header.sin Rules-quot   Makevars.template; do \
            /usr/bin/install -c -m 644 ./$file \
                            /root/QConf/agent/../deps/gdbm/_install/share/gettext/po/$file; \
          done; \
          for file in Makevars; do \
            rm -f /root/QConf/agent/../deps/gdbm/_install/share/gettext/po/$file; \
          done; \
        else \
          : ; \
        fi
make[1]: Leaving directory`/root/QConf/deps/gdbm/po'
Making install in src
make[1]: Entering directory `/root/QConf/deps/gdbm/src'
  YACC     gram.c
byacc: e - line 26 of "/root/QConf/deps/gdbm/src/gram.y", syntax error
%error-verbose
^
make[1]: *** [gram.c] Error 1
make[1]: Leaving directory`/root/QConf/deps/gdbm/src'
make: **\* [install-recursive] Error 1
CMake Error at driver/c++/CMakeLists.txt:29 (message):
  message called with incorrect number of arguments

-- Configuring incomplete, errors occurred!
See also "/root/QConf/build/CMakeFiles/CMakeOutput.log".
See also "/root/QConf/build/CMakeFiles/CMakeError.log".

**Comment by CatKang** [comment]
The error is happened when try to build gdbm, which is one of QConf dependencies.

You may go into QConf/deps/gdbm, run the ‘./configure, make, make install’ flow, and try to figure out the problem.

I guess you need an upgrade of byacc

**Comment by xuanskyer** [comment]
同样遇到这个问题，byacc的版本：
```
root@mini-centos6:gdbm$ [master] byacc -V
byacc - 1.9 20070509
```

**Comment by xuanskyer** [comment]
@kuaikuairen 如何解决的？

**Comment by CatKang** [comment]
进入QConf/deps/gdbm, 以此运行 ‘./configure, make, make install’
看看报错信息

**Comment by xuanskyer** [comment]
@CatKang 一样的。还是报那个语法错误。
```
  YACC     gram.c
byacc: e - line 26 of "/mnt/hgfs/github/QConf/deps/gdbm/src/gram.y", syntax error
%error-verbose
^
make[2]: *** [gram.c] 错误 1
make[2]: Leaving directory `/mnt/hgfs/github/QConf/deps/gdbm/src'
make[1]: *** [all-recursive] 错误 1
make[1]: Leaving directory `/mnt/hgfs/github/QConf/deps/gdbm'
make: *** [all] 错误 2
```

yacc版本：
```
root@mini-centos6:gdbm$ [master] byacc -V
byacc - 1.9 20070509
```

**Comment by xuanskyer** [comment]
解决了，还是软件依赖的问题：

```
yum install bison byacc flex texinfo libedit libtool libtool-ltdl-devel

```
