### ISSUE TITLE
./agent-cmd.sh: line 355: flock: command not found

### ISSUE THREAD

**Issue by Misfit-John** [Qihoo360/QConf#29]
./agent-cmd.sh start提示
./agent-cmd.sh: line 355: flock: command not found
本地环境是mac最新的OS X。是不支持mac吗？
原本以为是java driver的问题，后来发现agent没有起来。

**Comment by CatKang** [comment]
OSX没有flock命令，在agent-cmd.sh 里注释掉flock相关的两行即可

**Comment by Misfit-John** [comment]
Not fixed.

agent启动成功，但是qconf都无法init
```
Johns-MacBook-Pro:bin john$ ./agent-cmd.sh start
qconf_agent start.
```
[ERROR] Failed to init qconf! ret:201

**Comment by CatKang** [comment]
https://github.com/Qihoo360/QConf/wiki/FAQ 参考第二条

**Comment by Misfit-John** [comment]
谢谢，起来了。另外，关于这个flock和共享内存的设定，是不是可以考虑添加到README上面呢？毕竟这个问题应该广泛存在的。

**Comment by fightingbamboo** [comment]
https://www.kernel.org/pub/software/utils/script/flock/flock-2.0.1.tar.gz
源码 make & make install
可解决
