### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Qihoo360/QConf#3]
I would like to point out that identifiers like "[`__QCONF_CMD_H__`](https://github.com/Qihoo360/QConf/blob/535030bd5950e7a7d00a8c80932a184adf252d41/agent/qconf_cmd.h#L1)" and "[`__QCONF_COMMON_H__`](https://github.com/Qihoo360/QConf/blob/535030bd5950e7a7d00a8c80932a184adf252d41/base/qconf_common.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by haveTryTwo** [comment]
Thanks for your advise!
The "Noncompliant Code Example" : #define _MY_HEADER_H_ , and the reason why it's noncompliant is "The name may clash with reserved names defined by the implementation of the C++ standard template library in its headers or with reserved names implicitly predefined by the compiler even when no C++ standard library header is included";  and the macro defined in C++ standard template library may be like "#ifndef _GLIBCXX_ISTREAM" that begins with an underscore,  so avoiding using leading or trailing underscores in the name of the header guard may be compliant solution.
But this may be not only one compliant solution!  The 'Google C++ Style Guide'  advise  the symbol name should be <PROJECT>_<PATH>_<FILE>_H_. I think if it can achieve the purpose that not clash with reserved names defined by the C++ standard template, the macro that begins and ends with double underscore may be also ok.
Do you think so?

**Comment by elfring** [comment]
It is popular to use a suffix like "`_H`" for include guards. - There are better ways to make your identifiers reasonably unique.

Would you like to [avoid that your software depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Reconsider relevance of undefined behaviour")?

**Comment by haveTryTwo** [comment]
To make our identifiers unique, we'll take your advice, thanks again!

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/Qihoo360/QConf/commit/5bb5038858e7e8e16ffa88cf23d56221dae0ea9a "Deletion of underscores").
