### ISSUE TITLE
编译出错，因为-lssh

### ISSUE THREAD

**Issue by ops-ishumei** [Qihoo360/QConf#33]
ssh.c:(.text+0x268): undefined reference to `libssh2_session_block_directions'

改：
QConf-master/agent/CMakeLists.txt 
 66     ${PROJECT_SOURCE_DIR}/../deps/curl/_install/lib/libcurl.a )
为：
 66     ${PROJECT_SOURCE_DIR}/../deps/curl/_install/lib/libcurl.a -lssh2)

**Comment by CatKang** [comment]
可以提一个pull request，我和进代码里
