### ISSUE TITLE
qconf在docker使用中遇到重启后短暂性读取不到数据的问题

### ISSUE THREAD

**Issue by danlanxiaohei** [Qihoo360/QConf#35]
由于qconf是运行在容器中的，所以每次容器重启时，qconf服务也是重新启动的，这样导致项目运行起来后的一小段时间内，读取不到qconf中的数据。有没有办法解决呢？

**Comment by danlanxiaohei** [comment]
@CatKang 可以帮我看看吗？多谢。

**Comment by bigpyer** [comment]
重启系统(container)是会有这个情况的，但是读取不到数据的表现是什么？现在如果数据不存在，会阻塞直到读取到数据的?你说的问题是指这个阻塞吗？

**Comment by danlanxiaohei** [comment]
@bigpyer 比如我的应用程序在启动后需要先读取qconf中的一个配置地址，根据这个配置地址来初始化一个长链接，因为qconf也是刚启动嘛，这个时候去读取这个配置，可能会读出来的值为空。这时候我只能使用默认地址，而不是qconf中的最新值。而这个初始化，只在程序启动的时候执行一次，所以即便qconf后续同步下来这个数据了，我也不会再次读取，也就没法使用这个最新配置了。

**Comment by danlanxiaohei** [comment]
还有就是我看qconf有个dump文件，agent会定期把共享内存里的所有内容持久化到磁盘上的一个dump文件里。于是我就把容器内的dump文件路径挂载到了宿主机的一个目录上，但是宿主机的目录上只有一部分数据，运行一段时间后，还是有些数据获取不到。

**Comment by CatKang** [comment]
dump仅在共享内存中没有数据且zookeeper也连接不上的时候才会使用，这个动作是agent完成的。

qconf客户端接口获取数据，如果共享内存没有，会等待一段时间。通常这段时间内agent都能正常取到。

你现在的问题是这个时候agent还没有启动。所以尝试保证agent在业务程序之前启动吧
