### ISSUE TITLE
同步方法的超时时间是多少？

### ISSUE THREAD

**Issue by danlanxiaohei** [Qihoo360/QConf#36]
我在使用c++版本里qconf_get_allhost这个方法，请问这个方法有超时时间吗？因为是同步，总不能太长时间一直不返回吧。。。

**Comment by CatKang** [comment]
同步版本的接口，接口会等到agent获取数据，每次等5ms，等待100次，所以最多0.5s。

如果希望有更细致的控制，可以考虑异步版本的接口，发现没有会立即返回。有上层决定重试时间。
