### ISSUE TITLE
libssh2-dev 安装了，但是还是报错

### ISSUE THREAD

**Issue by bluebirdhsz** [Qihoo360/QConf#41]
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `ssh_block2waitfor':
ssh.c:(.text+0x258): undefined reference to`libssh2_session_block_directions'
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `sftp_send':
ssh.c:(.text+0x4fc): undefined reference to`libssh2_sftp_write'
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `sftp_recv':
ssh.c:(.text+0x5ac): undefined reference to`libssh2_sftp_read'
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `scp_send':
ssh.c:(.text+0x668): undefined reference to`libssh2_channel_write_ex'
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `scp_recv':
ssh.c:(.text+0x718): undefined reference to`libssh2_channel_read_ex'
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `ssh_statemach_act':

**Comment by CatKang** [comment]
https://github.com/Qihoo360/QConf/issues/33 可以看看这个是不是有效
