### ISSUE TITLE
qconf get_host是什么意思？

### ISSUE THREAD

**Issue by fengyindiehun** [Qihoo360/QConf#42]
执行qconf get_host 返回结果是
[ERROR]Failed to get get host! ret:10
请问是什么问题

**Comment by CatKang** [comment]
获取配置失败，可能是agent没有启动，配置不存在，网络不通等原因

**Comment by fengyindiehun** [comment]
agent已经启动了 qconf get_conf可以正常获得值， 请问get_host是获得idc下所有机器ip的意思吗？

**Comment by CatKang** [comment]
get_host 提供的是类似于服务发现的功能， 需要配合Monitor使用，可以参考http://catkang.github.io/2015/06/23/qconf.html 中倒数第二段内容
