### ISSUE TITLE
agent-cmd.sh: line 355: flock: command not found

### ISSUE THREAD

**Issue by guoshijie** [Qihoo360/QConf#49]
MacOS启动时报错：agent-cmd.sh: line 355: flock: command not found

**Comment by guoshijie** [comment]
解决了，注释掉flock那现行就ok了

**Comment by fightingbamboo** [comment]
https://www.kernel.org/pub/software/utils/script/flock/flock-2.0.1.tar.gz
源码 make & make install
可解决
