### ISSUE TITLE
Manager是否可以增加用户验证（用户名密码）

### ISSUE THREAD

**Issue by leeeboo** [Qihoo360/QConf#5]
Manager是否可以增加用户验证（用户名密码）？

**Comment by CatKang** [comment]
当前的manager界面只是一个简单的示例，完整功能的管理界面还没有开出，不知道提供开发界面用的接口是否可以满足，可以加讨论群438042718详细说

**Comment by leeeboo** [comment]
其实一个强大的管理平台很重要，我们是个初创团队，虽然自己开发一套界面没有太大技术问题，但是没有那么多人手。我们已经部署上了qconf并开始使用。

**Comment by CatKang** [comment]
好的，了解了，我们会考虑后续提供功能完善的管理界面

**Comment by liangshan** [comment]
其实简单点能在启动的时候限制一下只有内网访问就好了

**Comment by CatKang** [comment]
QConf的管理界面可以考虑zkdash， https://github.com/ireaderlab/zkdash
