### ISSUE TITLE
我在线上环境使用java api 老是报StackOverflowError

### ISSUE THREAD

**Issue by feigeai** [Qihoo360/QConf#50]
部分错误日志：
SEVERE: Servlet.service() for servlet [dispatcher] in context with path [/xxx] threw exception [Handler processing failed; nested exception is java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError
	at net.qihoo.qconf.Qconf.getConf(Native Method)
	at net.qihoo.qconf.Qconf.getConf(Unknown Source)

**Comment by CatKang** [comment]
运行机器是编译机器吗
