### ISSUE TITLE
php7 安装qconf manager 扩展报错

### ISSUE THREAD

**Issue by mufengit** [Qihoo360/QConf#52]
error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
 error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
 error: macro "add_assoc_string" passed 4 arguments, but takes just 3

php7 是否支持

**Comment by gaodq** [comment]
manager的PHP7支持还没做，可以参考一下客户端的PHP7支持：[https://github.com/Qihoo360/QConf/tree/master/driver/php](https://github.com/Qihoo360/QConf/tree/master/driver/php)
对manager的PHP扩展升级下[https://github.com/Qihoo360/QConf/tree/master/manager/src/php](https://github.com/Qihoo360/QConf/tree/master/manager/src/php)
