### ISSUE TITLE
undefined symbol: qconf_aget_allhost in Unknown on line 0

### ISSUE THREAD

**Issue by klein-xu** [Qihoo360/QConf#57]
编译参数: ./configure --with-php-config=/usr/bin/php-config --with-libqconf-dir=/usr/local/qconf/include --enable-static LDFLAGS=/usr/local/qconf/lib/libqconf.a
所在目录: QConf-1.2.0/driver/php

make test 时提示 undefined symbol: qconf_aget_allhost in Unknown on line 0

**Comment by CatKang** [comment]
应该是phpize和php-config的版本不一致
