### ISSUE TITLE
当修改一个配置的值时，怎么确保所有的client都能读到最新的值呢？

### ISSUE THREAD

**Issue by fdxuwei** [Qihoo360/QConf#58]
当修改一个配置的值时，怎么确保所有的client都能读到最新的值呢？
比如当agent从zookeeper同步数据失败时，本地程序将仍然使用老的配置在运行，但对zookeeper的修改却是成功的，让人以为本次修改成功。

**Comment by gaodq** [comment]
QConf确保本地共享内存与zk是同步的，可以配置反馈服务器来确保zk上的修改都到达了客户端

**Comment by springlie** [comment]
只看过文档，我理解 QConf 的 agent 在与 ZK 失去联系（网络中断）以后，为了保证一定的可用性，shared memory 的 cache 仍然维持着原有数据，以保证可用性。
LZ 需求是在这种情况之下，应用应该得到通知，然后自己决定如何进行操作（比如为了一致性，不使用 cache，而是一直重试与 ZK 同步等）。

**Comment by fdxuwei** [comment]
@gaodq 也只能这样了
