### ISSUE TITLE
是否考虑提供一些对 ZK 的写操作接口

### ISSUE THREAD

**Issue by springlie** [Qihoo360/QConf#59]
以满足“在应用中根据条件触发改变配置（可认为是状态），希望实时推送给其他应用，以期对其他应用造成影响”的场景。

**Comment by springlie** [comment]
或许可以在程序中直接使用 zk_node_set 之类的 API

**Comment by gaodq** [comment]
我们考虑QConf的agent是只读的，写操作只通过manager端进行，只在manager中提供set操作接口

**Comment by springlie** [comment]
如果在应用中直接应用 manager 的 API，应该也是 OK 的吧？将 manager 的 API 当做对 ZK C API 的封装来使用。

**Comment by gaodq** [comment]
恩可以的，可以试下:)
