### ISSUE TITLE
关灰度发布客户端的情况

### ISSUE THREAD

**Issue by kobe00712** [Qihoo360/QConf#60]
如果灰度发布，请问整个数据流程是什么样的。怎么影响到客户端

**Comment by CatKang** [comment]
详细见wiki：https://github.com/Qihoo360/QConf/wiki/QConf-%E7%81%B0%E5%BA%A6%E5%8F%91%E5%B8%83%E5%8A%9F%E8%83%BD%E8%AF%B4%E6%98%8E
