### ISSUE TITLE
agent和client程序同时访问共享内存中的哈希表，不用对哈希表加锁吗？

### ISSUE THREAD

**Issue by fdxuwei** [Qihoo360/QConf#61]
1、agent和client程序同时访问共享内存中的哈希表，不用对哈希表加锁吗？
2、对于哈希表中的单个节点，代码中采用md5校验的方式来保证并行读写的数据一致性，这种方法有理论支持吗？

**Comment by CatKang** [comment]
共享内存的所有写操作都在agent，client只读，所以不加锁可能导致的后果，按client读时机划分有三种：
1， client读到未写入的数据，为空或者是旧数据
2，client读到部分写入的数据
3，client读到完全写入的数据

其中1，3认为是Qconf的正常逻辑，2可以通过md5校验失败重读的方式转化为3
所以能够保证正确性
