### ISSUE TITLE
灰度发布grayBegin返回null

### ISSUE THREAD

**Issue by txl1290** [Qihoo360/QConf#63]
hi, @CatKang 

我在试用Qconf灰度发布功能时，发现gray_id返回的是null
文档中对参数hostname描述比较模糊，其他地方也没找到相关的教程。

调用代码如下：
```
<?php
                               
$qzk = new QConfZK("127.0.0.1:2181");
$machines = array("10.33.106.45");
$nodes = array("/demo/grey1" => "value1", "/demo/grey2" => "value2");

$gray_id = $qzk->grayBegin($nodes, $machines);

assert(0 === $qzk->grayCommit($gray_id));
```

请问，是不是我的用法不对。

**Comment by gaodq** [comment]
$machines 换用域名试试，https://github.com/Qihoo360/QConf/wiki/QConf-%E7%81%B0%E5%BA%A6%E5%8F%91%E5%B8%83%E5%8A%9F%E8%83%BD%E8%AF%B4%E6%98%8E

**Comment by gaodq** [comment]
/demo/grey1和/demo/grey2必须是已存在的节点
