### ISSUE TITLE
[go driver]安装问题

### ISSUE THREAD

**Issue by shejianmin** [Qihoo360/QConf#64]
帮忙看看这个问题怎么解决
[MacBook Pro src]$ go install infra/go_qconf
#infra/go_qconf
ld: library not found for -lqconf
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gaodq** [comment]
应该是c++库没安装
https://github.com/Qihoo360/QConf/tree/master/driver/c%2B%2B

**Comment by shejianmin** [comment]
谢谢
