### ISSUE TITLE
更新延迟的问题

### ISSUE THREAD

**Issue by cuihuan** [Qihoo360/QConf#67]
在使用的过程中，conf中的idc和local都已经修改了，但是，log中每次都要去调用之前的idc？这个是什么问题
2017/05/16 20:56:04 - [pid: 21704][ERROR][qconf_config.cc 400] - Failed to get conf! idc:test
2017/05/16 20:56:04 - [pid: 21704][ERROR][qconf_watcher.cc 690] - Failed to get host by idc:test`
`

**Comment by gaodq** [comment]
这个发生很频繁吗，应该是共享内存里有关于该idc的信息，然后qconf会定时与zk中的值比较更新，但如果idc配置变了，不会从内存中删掉，可以手动清空共享内存试试。1.2.1用ipcrm -M 0x10cf21d3，1.2.1之前用ipcrm -M 0x10cf21d1

**Comment by cuihuan** [comment]
1：共享内存清理了，然后重启就报找不到idc。
`
[xx qconf]# ipcs -m

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status
0x00000000 0          work       644        16400012   131        dest
0x10cf21d3 32769      work       644        16400012   0
[xx qconf]# ipcrm -M 0x10cf21d3
[xx qconf]# ipcs -m

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status
0x00000000 0          work       644        16400012   131        dest
`

2：之后对dump 里面的也清理了
依旧找不到

报错如下。
2017/05/18 14:21:00 - [pid: 9681][INFO][qconf_daemon.cc 135] - we try to keep alive for daemon process:9682
2017/05/18 14:21:00 - [pid: 9681][INFO][qconf_daemon.cc 150] - waiting for pid:9682
2017/05/18 14:21:00 - [pid: 9682][INFO][qconf_daemon.cc 126] - current child process id is 9682
2017/05/18 14:21:00 - [pid: 9682][ERROR][qconf_watcher.cc 411] - Failed to set watcher and update tbl!; data type:_, idc:, path:

**Comment by cuihuan** [comment]
或者能简单介绍，这块配置的加载原理吗？

现在用agend-cmd 启动后，日志总是报
```
2017/05/18 15:13:45 - [pid: 18671][ERROR][qconf_watcher.cc 411] - Failed to set watcher and update tbl!; data type:_, idc:, path:
```

已经配置了idc

**Comment by gaodq** [comment]
idc的配置是zookeeper.xxx = xxx形式的吗？

**Comment by cuihuan** [comment]
是的，也能获取到数据，方便留个联系方式，就是报watcher这个错误。

**Comment by cuihuan** [comment]
楼上，方便留个联系方式吗？方便调试下问题

**Comment by cuihuan** [comment]
zookeeper 的节点也有qconf的注册机器了。

**Comment by gaodq** [comment]
qq 279196771

**Comment by cuihuan** [comment]
楼主答复，这个error无关紧要，关。

```
2017/05/18 15:13:45 - [pid: 18671][ERROR][qconf_watcher.cc 411] - Failed to set watcher and update tbl!; data type:_, idc:, path:
```

**Comment by gaodq** [comment]
https://github.com/Qihoo360/Qconf/blob/master/agent/qconf_watcher.cc#L201
在进程退出的时候会向消息队列发一个"__STOP__"的特殊key用来向主线程发送信号，使其wait()语句结束阻塞，从而退出该线程。
但由于时序问题可能qconf退出时没有处理这个key请求，遗留在了消息队列里，然后下次重启qconf的时候就会有这个error

**Comment by YazaiHu** [comment]
> zookeeper 的节点也有qconf的注册机器了。

我mac下面启动成功了，但是发现没有在zk中注册节点成功，请问了解吗

**Comment by YazaiHu** [comment]
> > zookeeper 的节点也有qconf的注册机器了。
> 
> 我mac下面启动成功了，但是发现没有在zk中注册节点成功，请问了解吗

2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_agent.cc 49] - agent_dir:/usr/local/Cellar/qconf
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 52] - Map Content : pid: 94700
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - daemon_mode=1
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - feedback_enable=0
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - local_idc=test
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - log_level=1
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - max_repeat_read_times=100
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - register_node_prefix=/qconf/__qconf_register_hosts
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - script_execute_timeout=3000
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - shared_memory_size=100000
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - zk_log=zoo.err.log
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - zookeeper_recv_timeout=30000
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 52] - Map Content : pid: 94700
2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - test=127.0.0.1:2181
2019/11/06 11:16:30 - [pid: 94700][WARNING][qconf_config.cc 386] - Failed to get conf! key:log_fmt
qconf_agent start.

**Comment by YazaiHu** [comment]
> > > zookeeper 的节点也有qconf的注册机器了。
> > 
> > 
> > 我mac下面启动成功了，但是发现没有在zk中注册节点成功，请问了解吗
> 
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_agent.cc 49] - agent_dir:/usr/local/Cellar/qconf
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 52] - Map Content : pid: 94700
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - daemon_mode=1
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - feedback_enable=0
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - local_idc=test
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - log_level=1
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - max_repeat_read_times=100
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - register_node_prefix=/qconf/__qconf_register_hosts
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - script_execute_timeout=3000
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - shared_memory_size=100000
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - zk_log=zoo.err.log
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - zookeeper_recv_timeout=30000
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 52] - Map Content : pid: 94700
> 2019/11/06 11:16:30 - [pid: 94700][INFO][qconf_config.cc 56] - test=127.0.0.1:2181
> 2019/11/06 11:16:30 - [pid: 94700][WARNING][qconf_config.cc 386] - Failed to get conf! key:log_fmt
> qconf_agent start.

2019/11/06 11:16:29 - [pid: 94589][INFO][qconf_watcher.cc 1026] - Change trigger thread awaked, but no message found, maybe exit!
2019/11/06 11:16:29 - [pid: 94588][INFO][qconf_daemon.cc 164] - PID:94589 exited with exit_code:0
2019/11/06 11:16:29 - [pid: 94588][INFO][qconf_daemon.cc 168] - Child PID:94589 exited normally, now current PID:94588 exited!
2019/11/06 11:16:30 - [pid: 94702][INFO][qconf_daemon.cc 76] - success daemonize:94702
2019/11/06 11:16:30 - [pid: 94702][INFO][qconf_daemon.cc 135] - we try to keep alive for daemon process:94703
2019/11/06 11:16:30 - [pid: 94702][INFO][qconf_daemon.cc 150] - waiting for pid:94703
2019/11/06 11:16:30 - [pid: 94703][INFO][qconf_daemon.cc 126] - current child process id is 94703
2019/11/06 11:16:30 - [pid: 94703][ERROR][qconf_watcher.cc 411] - Failed to set watcher and update tbl!; data type:_, idc:, path:
