### ISSUE TITLE
触发script的问题

### ISSUE THREAD

**Issue by cuihuan** [Qihoo360/QConf#68]
添加script，新添加的节点。

如果qconf没有触发手动触发get_conf 该节点，zookeeper 变更，不会触发script。

这个有个全局获取数据的或者更新cache的策略吗？

**Comment by gaodq** [comment]
如果qconf没有触发手动触发get_conf 该节点
是什么意思

**Comment by cuihuan** [comment]
这个问题可能和
https://github.com/Qihoo360/QConf/issues/67

相关，本质应该是watcher 没有启动开！
