### ISSUE TITLE
java客户端使用

### ISSUE THREAD

**Issue by PeterPan-luo** [Qihoo360/QConf#70]
java客户端使用的时候怎么和zookeeper 进行连接？String value = Qconf.getConf(key);但是Qconf怎么和zookeeper连接呢？

**Comment by gaodq** [comment]
使用客户端之前需要安装agent，agent负责与zookeeper连接，客户端只是通过共享内存与agent通信

**Comment by PeterPan-luo** [comment]
现在win平台开发要自己在本地上编译agent吗？

**Comment by gaodq** [comment]
我们目前不打算支持win平台，可以参考一下#26 在Windows上使用QConf，http://blog.csdn.net/i_saw_you/article/details/50749591

**Comment by PeterPan-luo** [comment]
ok~
