### ISSUE TITLE
golang 

### ISSUE THREAD

**Issue by Hkesd** [Qihoo360/QConf#71]
在golang中引入该包按照官方提供的示例使用，发现编译没问题，一旦运行程序程序就自动kill掉
跟踪过进程，没什么收获

**Comment by gaodq** [comment]
agent启动了吗

**Comment by Hkesd** [comment]
启动了 用php的没什么问题， 本地的shell也能拿到

**Comment by gaodq** [comment]
是运行的QConf/driver/go/src/infra/demo/demo.go吗，我这能正常显示，是不是go环境有什么问题。qconf版本有变过吗，ipcrm -M 0x10cf21d1 0x10cf21d3尝试下删除共享内存后重启qconf。

**Comment by Hkesd** [comment]
我是引用了go_conf 这个包，编译没什么问题，运行就被kill掉了。mac环境下

**Comment by shejianmin** [comment]
我遇到过这种的问题，首先排除动态库问题。最终确认是编译参数的问题，用 go build -ldflags '-s' 命令编译以后就可以运行了，具体可以参考一下（go build -ldflags --help），希望可以帮到你。

**Comment by gaodq** [comment]
@Hkesd 请问按照 @shejianmin 的方法可以吗

**Comment by Hkesd** [comment]
@gaodq 应该是mac系统的问题，最近比较忙，没弄这个，过几天给答复，谢谢

**Comment by klein-xu** [comment]
@Hkesd ,也遇到了这个问题，能否告知解决方法？

**Comment by klein-xu** [comment]
已解决，GO升级到1.8.1以上版本就可以了
