### ISSUE TITLE
manager/php support do not Support PHP 7

### ISSUE THREAD

**Issue by seamanjiang** [Qihoo360/QConf#72]
erros occurs 

./configure  --with-php-config=/usr/local/php/bin/php-config --with-qconfzk-dir=/usr/local/qconf/manage/include --enable-static LDFLAGS=/usr/local/qconf/manage/lib/libqconf_zk.a

make

 g++ -I. -I/home/source/QConf/manager/src/php -DPHP_ATOM_INC -I/home/source/QConf/manager/src/php/include -I/home/source/QConf/manager/src/php/main -I/home/source/QConf/manager/src/php -I/usr/local/webserver/php/include/php -I/usr/local/webserver/php/include/php/main -I/usr/local/webserver/php/include/php/TSRM -I/usr/local/webserver/php/include/php/Zend -I/usr/local/webserver/php/include/php/ext -I/usr/local/webserver/php/include/php/ext/date/lib -I/usr/local/qconf/manage/include -I/usr/local/qconf/manage/include/zookeeper -DHAVE_CONFIG_H -g -O2 -c /home/source/QConf/manager/src/php/qconf_manager.cc  -fPIC -DPIC -o .libs/qconf_manager.o
/home/source/QConf/manager/src/php/qconf_manager.cc:157:73: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just
2
         RETURN_STRINGL(const_cast<char*>(value.c_str()), value.size(), 1);
                                                                         ^
/home/source/QConf/manager/src/php/qconf_manager.cc:203:77: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
         zend_hash_get_current_data(Z_ARRVAL_P(array_input), (void**) &z_item);
                                                                             ^
/home/source/QConf/manager/src/php/qconf_manager.cc:205:77: error: macro "zend_hash_get_current_key" passed 4 arguments, but
takes just 3
         if (zend_hash_get_current_key(Z_ARRVAL_P(array_input), &key, &idx, 0) == HASH_KEY_IS_STRING)
                                                                             ^
/home/source/QConf/manager/src/php/qconf_manager.cc:487:109: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
         add_assoc_string(return_data, const_cast<char*>((it->first).c_str()), (char*)(it->second).c_str(), 1);

**Comment by gaodq** [comment]
manager还没有支持PHP7

**Comment by seamanjiang** [comment]
do u have any plan to support php7?

thanks

**Comment by gaodq** [comment]
manager支持PHP7有不少人关注，接下来我们会做一下支持
