### ISSUE TITLE
Remove agent-cmd.sh

### ISSUE THREAD

**Issue by CatKang** [Qihoo360/QConf#78]
Remove agent-cmd.sh, directly execute binary with arguments.

**Comment by gaodq** [comment]
In fact, qconf_agent can start without agent-cmd.sh, we can keep it for the moment.
I add --localidc argument for qconf_agent. agent can start in frontend using command `./qconf_agent --localidc=test`.
Done. https://github.com/Qihoo360/QConf/commit/e229363e8f49fab92f0f16231b0e02aa22b0161a
