### ISSUE TITLE
cmake 出错，undefined reference to `pthread_create'

### ISSUE THREAD

**Issue by zhousoft** [Qihoo360/QConf#81]
`
Determining if the pthread_create exist failed with the following output:
Change Dir: /root/Downloads/QConf/manager/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec2402304754/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec2402304754.dir/build.make CMakeFiles/cmTryCompileExec2402304754.dir/build
gmake[1]: Entering directory `/root/Downloads/QConf/manager/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /root/Downloads/QConf/manager/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec2402304754.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTryCompileExec2402304754.dir/CheckSymbolExists.c.o   -c /root/Downloads/QConf/manager/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec2402304754
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2402304754.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTryCompileExec2402304754.dir/CheckSymbolExists.c.o  -o cmTryCompileExec2402304754 -rdynamic 
CMakeFiles/cmTryCompileExec2402304754.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0xc): undefined reference to `pthread_create'
collect2: ld 返回 1
gmake[1]: Leaving directory `/root/Downloads/QConf/manager/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [cmTryCompileExec2402304754] 错误 1
gmake: *** [cmTryCompileExec2402304754/fast] 错误 2

File /root/Downloads/QConf/manager/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:`
三台机器只有一台编译成功，查看了cmake和gcc的版本，三台是一样的

**Comment by gaodq** [comment]
gcc版本是多少，建议4.8以上
