### ISSUE TITLE
fatal error: gdbm.h: No such file or directory

### ISSUE THREAD

**Issue by disunlike** [Qihoo360/QConf#82]
# uname -a
Linux father 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linu

# history
> 533  git clone https://github.com/Qihoo360/QConf.git
> 534  cd QConf/
> 535  mkdir build && cmake .
> 536  make
# error
```
[root@father(eh0:192.168.132.137) QConf]#make
Scanning dependencies of target qconf_agent
[  2%] Building CXX object agent/CMakeFiles/qconf_agent.dir/qconf_dump.cc.o
/data/wwwroot/QConf/agent/qconf_dump.cc:1:18: fatal error: gdbm.h: No such file or directory
 #include <gdbm.h>
                  ^
compilation terminated.
agent/CMakeFiles/qconf_agent.dir/build.make:54: recipe for target 'agent/CMakeFiles/qconf_agent.dir/qconf_dump.cc.o' failed
make[2]: *** [agent/CMakeFiles/qconf_agent.dir/qconf_dump.cc.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'agent/CMakeFiles/qconf_agent.dir/all' failed
make[1]: *** [agent/CMakeFiles/qconf_agent.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by gaodq** [comment]
应该是gdbm编译有问题
cd QConf/deps/gdbm
./configure --prefix=$PWD/_install
make install

**Comment by ZhiGang-Fang** [comment]
agent/CMakeFiles/qconf_agent.dir/qconf_dump.cc.o
/Users/kevin/workspace/QConf/agent/qconf_dump.cc:1:10: fatal error: 'gdbm.h' file not found
#include <gdbm.h>
         ^~~~~~~~
1 error generated.
make[2]: *** [agent/CMakeFiles/qconf_agent.dir/qconf_dump.cc.o] Error 1
make[1]: *** [agent/CMakeFiles/qconf_agent.dir/all] Error 2
make: *** [all] Error 2
