### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by XiaLiangYong** [Qihoo360/QConf#83]
make[2]: Leaving directory `/usr/local/src/QConf/deps/gdbm/src'
make[1]: Leaving directory `/usr/local/src/QConf/deps/gdbm/src'
Making install in doc
make[1]: Entering directory `/usr/local/src/QConf/deps/gdbm/doc'
make[2]: Entering directory `/usr/local/src/QConf/deps/gdbm/doc'
make[2]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/usr/local/src/QConf/agent/../deps/gdbm/_install/share/info'
 /usr/bin/install -c -m 644 ./gdbm.info '/usr/local/src/QConf/agent/../deps/gdbm/_install/share/info'
 install-info --info-dir='/usr/local/src/QConf/agent/../deps/gdbm/_install/share/info' '/usr/local/src/QConf/agent/../deps/gdbm/_install/share/info/gdbm.info'
 /bin/mkdir -p '/usr/local/src/QConf/agent/../deps/gdbm/_install/share/man/man1'
 /usr/bin/install -c -m 644 gdbm_dump.1 gdbm_load.1 gdbmtool.1 '/usr/local/src/QConf/agent/../deps/gdbm/_install/share/man/man1'
 /bin/mkdir -p '/usr/local/src/QConf/agent/../deps/gdbm/_install/share/man/man3'
 /usr/bin/install -c -m 644 gdbm.3 '/usr/local/src/QConf/agent/../deps/gdbm/_install/share/man/man3'
make[2]: Leaving directory `/usr/local/src/QConf/deps/gdbm/doc'
make[1]: Leaving directory `/usr/local/src/QConf/deps/gdbm/doc'
Making install in tests
make[1]: Entering directory `/usr/local/src/QConf/deps/gdbm/tests'
make[2]: Entering directory `/usr/local/src/QConf/deps/gdbm/tests'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/usr/local/src/QConf/deps/gdbm/tests'
make[1]: Leaving directory `/usr/local/src/QConf/deps/gdbm/tests'
make[1]: Entering directory `/usr/local/src/QConf/deps/gdbm'
make[2]: Entering directory `/usr/local/src/QConf/deps/gdbm'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/usr/local/src/QConf/deps/gdbm'
make[1]: Leaving directory `/usr/local/src/QConf/deps/gdbm'
CMake Error at driver/c++/CMakeLists.txt:29 (message):
  message called with incorrect number of arguments

-- Configuring incomplete, errors occurred!
See also "/usr/local/src/QConf/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/QConf/CMakeFiles/CMakeError.log".

**Comment by gaodq** [comment]
gcc版本升到4.8以上
