### ISSUE TITLE
flask使用QConf问题

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Qihoo360/QConf#86]
在flask的web项目中能否在修改zookeeper的配置后，无需重启也能在web项目中更新配置？比如远程数据库ip地址等等

**Comment by gaodq** [comment]
是Python吗，可以看一下qconf Python的驱动https://github.com/Qihoo360/QConf/tree/master/driver/python
qconf是将zookeeper更新后的数据同步到共享内存，所以客户端不用重启

**Comment by SkyeBeFreeman** [comment]
@gaodq 所以是这个驱动使web应用配置更新？

**Comment by gaodq** [comment]
是qconf agent更新本地的共享内存，然后驱动去从共享内存中取最新的值
