### ISSUE TITLE
编译错误急，急、急

### ISSUE THREAD

**Issue by yfxu1990** [Qihoo360/QConf#87]
gcc 4.8
[  2%] Building CXX object agent/CMakeFiles/qconf_agent.dir/qconf_feedback.cc.o
[  4%] Linking CXX executable qconf_agent
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `ssh_block2waitfor':
ssh.c:(.text+0x268): undefined reference to `libssh2_session_block_directions'
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `sftp_send':
ssh.c:(.text+0x4ce): undefined reference to `libssh2_sftp_write'
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `sftp_recv':
ssh.c:(.text+0x56e): undefined reference to `libssh2_sftp_read'
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `scp_send':
ssh.c:(.text+0x61a): undefined reference to `libssh2_channel_write_ex'
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `scp_recv':
ssh.c:(.text+0x6ba): undefined reference to `libssh2_channel_read_ex'
../../agent/../deps/curl/_install/lib/libcurl.a(libcurl_la-ssh.o): In function `ssh_statemach_act':
ssh.c:(.text+0x9b0): undefined reference to `libssh2_session_set_blocking'
ssh.c:(.text+0x9ca): undefined reference to `libssh2_session_startup'
ssh.c:(.text+0xa0b): undefined reference to `libssh2_hostkey_hash'
ssh.c:(.text+0xa9e): undefined reference to `libssh2_session_hostkey'
ssh.c:(.text+0xaf9): undefined reference to `libssh2_knownhost_check'
ssh.c:(.text+0xc15): undefined reference to `libssh2_knownhost_free'
ssh.c:(.text+0xc35): undefined reference to `libssh2_agent_disconnect'
ssh.c:(.text+0xc55): undefined reference to `libssh2_agent_free'
ssh.c:(.text+0xc87): undefined reference to `libssh2_session_free'
ssh.c:(.text+0xe51): undefined reference to `libssh2_channel_free'
ssh.c:(.text+0xe94): undefined reference to `libssh2_session_disconnect_ex'
ssh.c:(.text+0xf01): undefined reference to `libssh2_channel_free'
ssh.c:(.text+0xf51): undefined reference to `libssh2_channel_wait_closed'
ssh.c:(.text+0xf91): undefined reference to `libssh2_channel_send_eof'
ssh.c:(.text+0xfd1): undefined reference to `libssh2_channel_wait_eof'
ssh.c:(.text+0x104c): undefined reference to `libssh2_scp_recv'
ssh.c:(.text+0x11bb): undefined reference to `libssh2_sftp_symlink_ex'
ssh.c:(.text+0x1289): undefined reference to `libssh2_sftp_close_handle'
ssh.c:(.text+0x1329): undefined reference to `libssh2_sftp_stat_ex'

**Comment by gaodq** [comment]
什么操作系统，看起来是libssh2没有安装

**Comment by yfxu1990** [comment]
rethat el6 ,我把主CMakelist中的 --without ssh2 ，编译ok了，不知道使用起来会不会有什么影响？

**Comment by yfxu1990** [comment]
@gaodq

**Comment by gaodq** [comment]
不会有影响，这个是libcurl.a用的，主要是反馈结果用的。

**Comment by yfxu1990** [comment]
@gaodq 好的谢谢
