### ISSUE TITLE
使用golang版本遇到的超时问题

### ISSUE THREAD

**Issue by jseanj** [Qihoo360/QConf#94]
在调用GetConf接口时，如果对应的key不存在会返回 "Failed to find key on given idc" 这样的错误，但是会大概500ms才返回，而如果key存在，大概0.01ms就会返回，怎样避免出现错误引起的超时呢？

**Comment by gaodq** [comment]
如果找不到key，qconf会去zk尝试获取，这时接口是同步等待的，也就是500ms超时
golang没有封装异步接口，你可以看一下自己更新具体就是用这个qconf_aget_conf接口
模仿这个接口
https://github.com/Qihoo360/QConf/blob/e3890ce9ad40f701fdbabd466788197312fddc3c/driver/go/src/infra/go_qconf/go_qconf.go#L166
用这个c接口
https://github.com/Qihoo360/QConf/blob/e3890ce9ad40f701fdbabd466788197312fddc3c/driver/c%2B%2B/src/qconf.cc#L63

**Comment by jseanj** [comment]
@gaodq 谢谢，了解了。我现在是在上层加了个超时。

**Comment by LuoHongLiang0921** [comment]
你好，楼主。了解下，目前还有在使用 QConf 吗？我最近 在 mac 上安装，不成功。问了官方 也没有反馈。看这个开源的项目已经好久不更新了。
